# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0003_auto_20170313_1314'),
        ('file', '0003_auto_20180516_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresponse',
            name='device_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileresponse',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileresponse',
            name='file_input',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='file.FileInput', to_field='datafile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileresponse',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinput',
            name='datafile',
            field=models.FileField(unique=True, upload_to=file.models.directory_path),
        ),
    ]
