# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20180516_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresponse',
            name='file_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.FileInput'),
        ),
    ]
