# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20180516_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinput',
            name='loops',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
